### ISSUE TITLE
New client messages not shown until selection of another channel

### ISSUE THREAD

**Issue by jagosta** [ogra1/mattermost-client#2]
I had a case where someone wrote me a "new" private channel message. The client would not show that message folder (or obviously the message) until I selected another channel.

The client was maximized, but the window focus was on another window.  I received a gnome window manager pop up notification that I received a new mattermost message, but when I scrolled through my mattermost client I could not see any new messages.  I then selected a different channel in the client UI, and this resulted in the new private folder now showing up in the client with the new message.

**Comment by ogra1** [comment]
this is nothing i can do anything about, the website you see is not under my control.

all the snap does is to provide the "frame" around it but it does nothing *inside* the site itself (imagine a standalone browser tab that pretends to be an app), if the channel list does not properly refresh that is rather a bug on the mattermost side ...
